controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

test_route:
  path: /hello
  controller: App\Controller\HelloController::sayHello
